version: '3.8'
services:
  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/data

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CHROMA_URL=http://chroma:8000
    volumes:
      - .:/app
      - /app/node_modules # PENTING: Menjaga node_modules tetap versi Linux Slim
    depends_on:
      - chroma